title: FINDS Lab
description: "Financial Data Science Lab."

# 사이트 기본 URL (GitHub Pages 도메인)
url: "https://finds-lab.github.io"

# 프로젝트 페이지니까 반드시 repo 이름 붙여야 함
baseurl: "/website"

# (선택) 테마가 필요 없다면 주석 처리
# theme: minima
# _config.yml
collections:
  news:
    output: true
    permalink: /news/:name.html

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: news_post   # 개별 뉴스 페이지 기본 레이아웃
